<?php

/**
 *@file
 *article.module
 *
 */
function twitter_block_info(){
  // This example comes from node.module.
  $blocks['articles'] = array(
    'info' => t('Twitter Module'),
  );

  return $blocks;
}

function twitter_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'articles':
      Global $base_url;

      // Agregar funcionalidad (desde bd) de la twitter

      // Get current path
      $path = current_path();
      if($path == "node/6"){
        $section = "
        <div class='twitter_container'>
          <p class='twitter_text'> Twitter </p>
        </div>
        ";
        $block['subject'] = t(''); //This is twitter  Block
        $block['content'] = $section;
      }

      break;
  }
  return $block;
}
