<?php

/**
 *@file
 *article.module
 *
 */
function regiones_section_block_info(){
  // This example comes from node.module.
  $blocks['articles'] = array(
    'info' => t('Regiones Section Module'),
  );

  return $blocks;
}

function regiones_section_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'articles':
    Global $base_url;
    $url_site = "http://".$_SERVER['HTTP_HOST'];

    $parent = 89;
    $rnames_query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, A.title, B.field_categories_value, C.field_category_parent_value 
                     FROM {node} A 
                     LEFT JOIN {field_data_field_categories} B ON A.nid = B.entity_id 
                     LEFT JOIN {field_data_field_category_parent} C ON A.nid = C.entity_id
                     WHERE A.status = 1 
                     AND A.type = :type 
                     AND (A.title like 'Región%' OR A.title like 'Region%')
                     AND C.field_category_parent_value = :parent 
                     ORDER BY nid ASC";
    $rnames = db_query($rnames_query, array(':type' => 'clasificacion_articulos', ':parent' => $parent))->fetchAll();
    // print_r('region names: ');
    // print_r($rnames);

    $regionesTotal = sizeof($rnames);

    $regionesTitles = array();
    foreach ($rnames as $rname) {

      $rWords = explode(" ", $rname->title);
      $rWTotal = sizeof($rWords);
      
      if($rWTotal > 1){
        
        $rTitle = '';
        for($rw_i = 1; $rw_i <= $rWTotal; $rw_i++) {
          $rTitle .= $rWords[$rw_i].' '; 
        }

        $rObj = array('id' => $rname->nid,
                      'title' => $rTitle);
        
        array_push($regionesTitles, $rObj);
      }
    }
    
    // print_r($regionesTitles);
    $regiones = array();

    for($i = 0; $i < $regionesTotal; $i++){
      //$item = $i+1;
      $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, A.title, B.entity_id, B.field_categories_value, C.field_home_display_value  
                FROM {node} A 
                LEFT JOIN {field_data_field_categories} B ON A.nid = B.entity_id 
                LEFT JOIN {field_data_field_home_display} C ON A.nid = C.entity_id 
                WHERE A.status = 1
                AND A.type = :type 
                AND C.field_home_display_value = 1 
                AND B.field_categories_value like '%".$regionesTitles[$i]['id']."%' 
                ORDER BY nid DESC LIMIT 1";
      $region = db_query($query, array(':type' => 'articulo'))->fetchAll();

      if(!empty($region)){
        $a_id = $region[0]->nid;

        // Execute queries to get slide info: image, title (description).
        if (is_numeric($a_id)){

          // Get: Image.
          $image = db_query("SELECT entity_id, revision_id, field_image_profile_fid FROM {field_data_field_image_profile} WHERE entity_id = :eid", array(':eid' => $a_id))->fetchObject();

          $i_fid = $image->field_image_profile_fid;
          if (is_numeric($i_fid)){
            $image_profile_file = db_query("SELECT fid, uid, filename FROM {file_managed} WHERE fid = :fid", array(':fid' => $i_fid))->fetchObject();
            $image_file = $image_profile_file->filename;
          }
          else{
            $image_file = "gente.png"; //default image 
          }

          // Get: Title (description).
          $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, A.title, B.entity_id, B.field_title_value FROM {node} A INNER JOIN {field_data_field_title} B ON A.nid = B.entity_id WHERE B.entity_id = :e_id";
          $title_field = db_query($query, array(':e_id' => $a_id))->fetchObject();
          $title = $title_field->title;
        }
        else{
          $image_file = "gente.png"; //default image 
          $title = "No title"; //default title
        }        
      }
      else{
        $image_file = "gente.png";
        $title = "No title";
      }

      $image_url = '"'.$base_url.'/sites/default/files/'.$image_file.'"';
      $region[0]->image_name = $image_file;
      $region[0]->image_url  = $image_url;

      $region[0]->description = $title; 

      $region[0]->title = $regionesTitles[$i]['title'];

      array_push($regiones, $region);
    }

    // print_r('regiones -> ');
    // print_r($regiones);

    // Get current path
    $path = current_path();
    if($path == "node/6"){
      //regiones_slider
      $section = "
      <div class='regiones_section'>
        <div class='regiones_title'> 
          <p> Regiones </p>
        </div>
        <div class='regiones_container'>";
      $section .= "<div class='regiones_slider'>";

      foreach ($regiones as $region) {
        // Link: Redirect to HOME if the article validation is empty.
        $section .= "
          <a href='".$url_site."/node/".$region[0]->nid."'>
            <div class='regiones_slide'>
              <div class='regiones_content ".$region[0]->title."'> 
                <p class='regiones_content_title'> ".$region[0]->title." </p>
                <div class='regiones_content_image' style='background-image: url(".$region[0]->image_url.");'> </div>
                <p class='regiones_content_description'> ".$region[0]->description." </p>                
              </div>
            </div>
          </a>";
      }

      $section .= "</div>";
      $section .= "
        </div>
      </div>";

      $block['subject'] = t(''); //This is regiones Section Block
      $block['content'] = $section;
    }
      break;
  }
  return $block;
}
