<?php

/**
 *@file
 *article.module
 *
 */
function recent_articles_slider_block_info(){
  // This example comes from node.module.
  $blocks['articles'] = array(
    'info' => t('Recent Articles Slider'),
  );

  return $blocks;
}

function recent_articles_slider_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'articles':
    Global $base_url;
    $url_site = "http://".$_SERVER['HTTP_HOST'];

    // Query to get article nodes (TO DO: Last 5 nodes with cover validation: ifnot add other(s)*)
    $articles = db_query("SELECT A.nid, A.vid, A.uid, A.type, A.status, A.title, B.field_home_display_value
                          FROM {node} A
                          INNER JOIN {field_data_field_home_display} B ON A.nid = B.entity_id 
                          WHERE A.status = 1
                          AND A.type = :type
                          AND B.field_home_display_value = 1  
                          ORDER BY nid DESC 
                          LIMIT 5", array(':type' => 'articulo'))->fetchAll();

    // Cover image slides array
    $slides = array();

    // Go over each article node (TO DO: Get the extra info: title, description)
    foreach ($articles as $article){
    	$a_id = $article->nid;

    	// Execute queries to get slide info: image, title and description.
    	if (is_numeric($a_id)){

        // Get: Image.
    		$image_cover = db_query("SELECT entity_id, revision_id, field_image_cover_fid FROM {field_data_field_image_cover} WHERE entity_id = :eid", array(':eid' => $a_id))->fetchObject();

	    	$ic_fid = $image_cover->field_image_cover_fid;
    		if (is_numeric($ic_fid)){
		    	$image_cover_file = db_query("SELECT fid, uid, filename FROM {file_managed} WHERE fid = :fid", array(':fid' => $ic_fid))->fetchObject();
          $image = $image_cover_file->filename;
			  }
		    else {
		    	$image = "no page"; //change for a _default_ image *
		    }

        // Get Cover position.
        $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, B.entity_id, B.field_cover_position_value FROM {node} A INNER JOIN {field_data_field_cover_position} B ON A.nid = B.entity_id WHERE B.entity_id = :e_id";
        $cover_field = db_query($query, array(':e_id' => $a_id))->fetchObject();
        $cover_position = $cover_field->field_cover_position_value;

        // Get: Title.
        $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, A.title, B.entity_id, B.field_title_value FROM {node} A INNER JOIN {field_data_field_title} B ON A.nid = B.entity_id WHERE B.entity_id = :e_id";
        $title_field = db_query($query, array(':e_id' => $a_id))->fetchObject();
        $title = $title_field->title;

        // Get: Description).
        $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, B.entity_id, B.field_description_value FROM {node} A INNER JOIN {field_data_field_description} B ON A.nid = B.entity_id WHERE B.entity_id = :e_id";

        $description_field = db_query($query, array(':e_id' => $a_id))->fetchObject();
        $description = $description_field->field_description_value;        
    	}
    	else{
    		$image = "no page"; //change for a _default_ image *
        $cover_position = "center";
        $title = 'T&iacute;tutlo';
        $description = 'Descripci&oacute;n';
    	}
      
      $slide = array(
        "id"    => $a_id,
        "cover" => $image,
        "cover_position" => $cover_position,
        "title" => $title,            
        "description" => $description,
      );
      array_push($slides, $slide);
	  }

    // Get current path
    $path = current_path();

    if($path == "node/6"){

      $slider = "<div class='recent_slider'>";
      foreach ($slides as $slide) {
        $url = '"'.$base_url.'/sites/default/files/'.$slide['cover'].'"';

        // Link: Redirect to HOME if the article validation is empty.
        $slider .= 
        " <a href='".$url_site."/node/".$slide['id']."'>
            <div class='recent_slide'>
            	<div class='recent_slide_background' style='background-image: url(".$url."); background-position: ".$slide['cover_position'].";'>
                <div class='recent_slide_info'>
                  <div class='recent_slide_wrapper'>
                    <p class='slide_title'>".$slide['title']."</p>
                    <p class='slide_description'>".$slide['description']."</p>
                  </div>
                </div>
              </div>
            </div>
          </a>";
      }
      $slider .= "</div>";

      $block['subject'] = t(''); //This is my Recent Articles Slider Block
      $block['content'] = $slider;
    }
    break;
  }
  return $block;
}
